development:
  adapter: mysql2
  encoding: utf8
  database: tapout_dev
  username: root
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: tapout_test
  username: root

production:
  adapter: mysql2
  encoding: utf8
  database: tapout
  username: root
  pool: 5
